<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THE_EXPANDABLES" ignored="0" name="TestRetry" tests="6" failures="2" timestamp="18 Jul 2023 12:32:55 GMT" time="0.078" errors="0">
  <testcase name="test1" time="0.016" classname="com.practice.session1.RetryListnerCheck">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="com.practice.session1.RetryListnerCheck">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="com.practice.session1.RetryListnerCheck">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.practice.session1.RetryListnerCheck.test1(RetryListnerCheck.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="com.practice.session1.RetryListnerCheck">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="com.practice.session1.RetryListnerCheck">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="com.practice.session1.RetryListnerCheck">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.practice.session1.RetryListnerCheck.test2(RetryListnerCheck.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- TestRetry -->
